adevsrc@pcm0c=format=nuttx:sample_rate=48000:ch_layout=stereo:devname=/dev/audio/pcm0c:map=1,volume@VolAcap=precision=fixed[acap0],
[acap0]abufsink@acap;

abufsrc@apb=map=1,volume@VolApb=precision=fixed[apb0],
[apb0]adevsink@pcm0p=format=nuttx:sample_rate=48000:ch_layout=stereo:devname=/dev/audio/pcm0p
