#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE
#define LV_USE_LOG 0
#define LV_USE_SYSMON 0
#define LV_USE_NUTTX 0
#define LV_USE_FREETYPE 1
#define LV_USE_FS_POSIX 1
#define LV_FS_POSIX_LETTER '/'
#define LV_FS_POSIX_PATH "/"
#define LV_CACHE_DEF_SIZE (1024 * 1024)
#define LV_FREETYPE_CACHE_FT_GLYPH_CNT 256
#define LV_FONT_SIMSUN_16_CJK 1
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_THORVG_EXTERNAL 0
#define LV_USE_DRAW_SW 1
#define LV_USE_DRAW_SW_ASM LV_DRAW_SW_ASM_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#endif
