/* Generated by tools/split_layered_avatar.py. Coordinates are canvas-local. */
#ifndef QIJI_LAYER_ASSETS_H
#define QIJI_LAYER_ASSETS_H
static const struct { const char *name; int x, y, w, h, px, py; } qiji_layer_assets[] = {
    {"legs", 55, 182, 64, 82, 87, 183},
    {"braid_l", 20, 83, 46, 61, 50, 89},
    {"braid_r", 109, 83, 47, 61, 126, 89},
    {"body", 53, 89, 69, 99, 87, 181},
    {"neck", 76, 90, 25, 17, 87, 100},
    {"head", 36, 8, 104, 94, 87, 97},
    {"eye_l", 56, 63, 26, 21, 87, 97},
    {"eye_r", 95, 63, 25, 21, 87, 97},
    {"brows", 64, 48, 53, 7, 87, 97},
    {"mouth_closed", 80, 83, 17, 7, 87, 97},
    {"bangs", 42, 19, 81, 52, 87, 97},
    {"arms", 35, 115, 108, 75, 87, 110},
    {"eye_closed_l", 56, 63, 26, 21, 87, 97},
    {"eye_closed_r", 95, 63, 25, 21, 87, 97},
    {"mouth_small", 80, 83, 17, 7, 87, 97},
    {"mouth_large", 80, 83, 17, 7, 87, 97},
};
#endif
