"""Render vendored Google Material Icons Round SVGs to tiny LVGL image arrays.

Host dependencies: pillow, resvg-py. No network or API keys are required.
"""
from pathlib import Path
from io import BytesIO
import resvg_py
from PIL import Image

project = Path(__file__).resolve().parents[1]
source = project / 'assets/material-icons'
lines = ['/* Google Material Design Icons, Apache-2.0. See assets/material-icons/LICENSE. */',
         '/* Generated by tools/convert_material_icons.py; do not edit by hand. */',
         '#ifndef QIJI_MATERIAL_ICONS_H', '#define QIJI_MATERIAL_ICONS_H', '#include "lvgl.h"']
for name in ('mic', 'stop', 'more_horiz'):
    png = resvg_py.svg_to_bytes(svg_path=str(source / (name + '.svg')), width=24, height=24)
    alpha = Image.open(BytesIO(png)).convert('RGBA').getchannel('A')
    white = Image.new('RGBA', (24, 24), (255, 255, 255, 255))
    white.putalpha(alpha)
    white.save(source / (name + '.png'))
    data = bytes([255, 255]) * (24 * 24) + alpha.tobytes()
    lines.append('static const uint8_t material_' + name + '_data[] = {')
    lines.extend('    ' + ','.join('0x%02x' % b for b in data[i:i+24]) + ','
                 for i in range(0, len(data), 24))
    lines += ['};', 'static const lv_image_dsc_t material_' + name + ' = {',
              '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565A8,',
              '                .w = 24, .h = 24, .stride = 48 },',
              '    .data_size = sizeof(material_' + name + '_data),',
              '    .data = material_' + name + '_data', '};']
lines.append('#endif')
(project / 'app/gemini_chat_minimal/qiji_material_icons.h').write_text('\n'.join(lines) + '\n')
print('Converted 3 official Material Icons to embedded 24px RGB565A8 images')
